# Generated by Django 6.0.7 on 2026-07-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], default='Buy', max_length=10),
        ),
    ]
